version: "3.7"
services:
  # 123done:
  #   image: 123done:build
  #   command: node server.js
  #   environment:
  #     - CONFIG_123DONE=./config-local.json
  #     - NODE_ENV=dev
  #     - PORT=8080
  #   init: true
  #   ports:
  #     - "8080:8080"
  browserid-verifier:
    image: fxa-mono:build
    command: node /fxa/packages/browserid-verifier/server.js
    environment:
      - PORT=5050
      - IP_ADDRESS=0.0.0.0
      - FORCE_INSECURE_LOOKUP_OVER_HTTP=true
    init: true
    ports:
      - "5050:5050"
  auth:
    image: fxa-mono:build
    entrypoint: /bin/bash -c
    command: ["/fxa/_scripts/check-mysql.sh 3306 mysql && node /fxa/packages/db-migrations/bin/patcher.mjs && node /fxa/packages/fxa-auth-server/dist/fxa-auth-server/bin/key_server.js"]
    environment:
      - PORT=9000
      - NODE_ENV=dev
      - IP_ADDRESS=0.0.0.0
      - DB=mysql
      - CONFIG_FILES=config/secrets.json
      - AUTH_MYSQL_HOST=mysql
      - MYSQL_HOST=mysql
      - MEMCACHE_METRICS_CONTEXT_ADDRESS=memcached:11211
      - EMAIL_SERVICE_HOST=email
      - REDIS_HOST=redis
      - ACCESS_TOKEN_REDIS_HOST=redis
      - REFRESH_TOKEN_REDIS_HOST=redis
      - SMTP_HOST=maildev
      - SMTP_PORT=25
      - SNS_TOPIC_ENDPOINT=http://goaws:4100
      - MJML_ENABLED_EMAIL_ADDRESS=.+@mozilla\.com
    init: true
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - mysql
  content:
    image: fxa-mono:build
    command: node /fxa/packages/fxa-content-server/server/bin/fxa-content-server.js
    environment:
      - PORT=3030
      - NODE_ENV=production
      - FEATURE_FLAGS_REDIS_HOST=redis
      - STATIC_DIRECTORY=dist
      - PAGE_TEMPLATE_SUBDIRECTORY=dist
      - CONFIG_FILES=/fxa/packages/fxa-content-server/server/config/production.json
    init: true
    ports:
      - "3030:3030"
    depends_on:
      - redis
  profile:
    image: fxa-mono:build
    entrypoint: /bin/bash -c
    command: ["/fxa/_scripts/check-url.sh auth:9000/__version__ && node /fxa/packages/fxa-profile-server/bin/server.js"]
    environment:
      - HOST=0.0.0.0
      - PORT=1111
      - DB=mysql
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - WORKER_HOST=profile-worker
      - WORKER_URL=http://profile-worker:1113
      - REDIS_HOST=redis
      - AUTH_SERVER_URL=http://auth:9000/v1
      - OAUTH_SERVER_URL=http://auth:9000/v1
    init: true
    ports:
      - "1111:1111"
    depends_on:
      - auth
      - mysql
      - memcached
  profile-worker:
    image: fxa-mono:build
    entrypoint: /bin/bash -c
    command: ["/fxa/_scripts/check-url.sh auth:9000/__version__ && node /fxa/packages/fxa-profile-server/bin/worker.js"]
    environment:
      - WORKER_HOST=0.0.0.0
      - WORKER_PORT=1113
      - DB=mysql
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - AUTH_SERVER_URL=http://auth:9000/v1
      - OAUTH_SERVER_URL=http://auth:9000/v1
    init: true
    ports:
      - "1113:1113"
    depends_on:
      - auth
      - mysql
      - memcached
  profile-static:
    image: fxa-mono:build
    entrypoint: /bin/bash -c
    command: ["/fxa/_scripts/check-url.sh auth:9000/__version__ && node /fxa/packages/fxa-profile-server/bin/_static.js"]
    environment:
      - HOST=0.0.0.0
      # yes, port is intentionally set to 1111
      - PORT=1111
      - DB=mysql
      - NODE_ENV=development
      - MYSQL_HOST=mysql
    init: true
    ports:
      - "1112:1112"
    depends_on:
      - auth
      - mysql
      - memcached
  graphql-api:
    image: fxa-mono:build
    entrypoint: /bin/bash -c
    command: ["/fxa/_scripts/check-url.sh auth:9000/__version__ && node /fxa/packages/fxa-graphql-api/dist/main.js"]
    environment:
      - PORT=8290
      - AUTH_MYSQL_HOST=mysql
      - PROFILE_MYSQL_HOST=mysql
      - OAUTH_MYSQL_HOST=mysql
      - AUTH_SERVER_URL=http://auth:9000/v1
      - PROFILE_SERVER_URL=http://profile:1111/v1
      - ACCESS_TOKEN_REDIS_HOST=redis
      - CUSTOMS_SERVER_URL=none
      - CORS_ORIGIN=http://localhost:3030
    depends_on:
      - auth
      - profile
      - mysql
      - redis
    ports:
      - "8290:8290"
  redis:
    image: redis
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=fxa
  memcached:
    image: memcached
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
  goaws:
    image: pafortin/goaws
  pubsub:
    image: knarz/pubsub-emulator:latest
    ports:
      - "8085:8085"
  firestore:
    image: jdlk7/firestore-emulator
    ports:
      - "9090:9090"
