---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fxa-auth-server
  description: Auth Server back-end for Mozilla Accounts
  tags:
    - typescript
    - javascript
    - node
    - hapi
  annotations:
    sentry.io/project-slug: mozilla/fxa-auth-server
    circleci.com/project-slug: github/mozilla/fxa
spec:
  type: service
  lifecycle: production
  owner: fxa-team
  system: mozilla-accounts
  dependsOn:
    - component:fxa-browserid-verifier
    - component:fxa-customs-server
    - resource:fxa-auth-database
    - resource:fxa-oauth-database
    - resource:fxa-pushbox-database
    - resource:fxa-stripe-database
    - resource:fxa-auth-cache
