enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

packageExtensions:
  fxa-pairing-channel@*:
    dependencies:
      webpack: ^4.43.0
  "@types/react-dom@^17.0.4":
    dependencies:
      "@types/react": "^17.0.14"
    peerDependenciesMeta:
      "@types/react": 
        optional: true
  "@types/reach__router@^1.3.11":
    dependencies:
      "@types/react": "^17.0.14"
    peerDependenciesMeta:
      "@types/react": 
        optional: true


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
