receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    loglevel: debug
  otlphttp:
    endpoint: "jaeger.fxa:43180"
    tls:
      insecure: true

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      # Set env EXPORTERS to toggle exporters. ie to turn all exporters set as:
      #    EXPORTERS=logging,jaeger,googlecloud
      exporters: '${EXPORTERS}'
